#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MAS_CONDA_ENV_PATH="${MAS_CONDA_ENV_PATH:-/tmp/mas_4xh20_from_py312}"
CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0,1,2,3}"
RUN_STAMP="$(date -u +%Y%m%dT%H%M%SZ)"
RUN_DIR="${MAS_RUN_DIR:-${PROJECT_ROOT}/runs/full_suite_${RUN_STAMP}}"
ENV_PYTHON="${MAS_CONDA_ENV_PATH}/bin/python"
ITT_PRELOAD_SO="${MAS_ITT_PRELOAD_SO:-${MAS_CONDA_ENV_PATH}/lib/libittnotify.so}"

mkdir -p "${RUN_DIR}"
mkdir -p "${RUN_DIR}/logs"
mkdir -p "${RUN_DIR}/plots"

if [[ ! -x "${ENV_PYTHON}" ]]; then
  echo "找不到 Python 环境: ${MAS_CONDA_ENV_PATH}" >&2
  exit 1
fi

if [[ ! -f "${ITT_PRELOAD_SO}" ]]; then
  echo "找不到 ITT 共享库: ${ITT_PRELOAD_SO}" >&2
  exit 1
fi

PYTHONPATH_VALUE="${PROJECT_ROOT}"
LANG_VALUE="${LANG:-C.UTF-8}"
TERM_VALUE="${TERM:-xterm-256color}"
PATH_VALUE="${MAS_CONDA_ENV_PATH}/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
PYTORCH_CUDA_ALLOC_CONF_VALUE="${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True}"
MAS_LOG_DIR_VALUE="${MAS_LOG_DIR:-${RUN_DIR}/logs}"
MAS_PLOT_DIR_VALUE="${MAS_PLOT_DIR:-${RUN_DIR}/plots}"
MAS_THREE_LAYER_DEBUG_PRINT_VALUE="${MAS_THREE_LAYER_DEBUG_PRINT:-0}"
MAS_PARALLEL_MODE_VALUE="${MAS_PARALLEL_MODE:-three_layer_workers}"
MAS_POLICY_DEVICE_MAP_VALUE="${MAS_POLICY_DEVICE_MAP:-agent0.pi0:0,agent0.pi1:1,agent1.pi0:2,agent1.pi1:3}"
MAS_GLOBAL_SEED_VALUE="${MAS_GLOBAL_SEED:-1234}"

echo "PROJECT_ROOT=${PROJECT_ROOT}"
echo "MAS_CONDA_ENV_PATH=${MAS_CONDA_ENV_PATH}"
echo "ENV_PYTHON=${ENV_PYTHON}"
echo "ITT_PRELOAD_SO=${ITT_PRELOAD_SO}"
echo "CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES}"
echo "RUN_DIR=${RUN_DIR}"
echo "MAS_TRAIN_VAL_TOTAL_LIMIT=${MAS_TRAIN_VAL_TOTAL_LIMIT:-<full>}"
echo "MAS_TEST_SAMPLE_LIMIT=${MAS_TEST_SAMPLE_LIMIT:-<full>}"
echo "MAS_THREE_LAYER_DEBUG_PRINT=${MAS_THREE_LAYER_DEBUG_PRINT_VALUE}"
echo "MAS_PARALLEL_MODE=${MAS_PARALLEL_MODE_VALUE}"
echo "MAS_POLICY_DEVICE_MAP=${MAS_POLICY_DEVICE_MAP_VALUE}"
echo "MAS_GLOBAL_SEED=${MAS_GLOBAL_SEED_VALUE}"

CMD=(
  env -i
  "PATH=${PATH_VALUE}"
  "HOME=${HOME:-/root}"
  "LANG=${LANG_VALUE}"
  "TERM=${TERM_VALUE}"
  "PYTHONUNBUFFERED=1"
  "PYTHONPATH=${PYTHONPATH_VALUE}"
  "LD_PRELOAD=${ITT_PRELOAD_SO}"
  "CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES}"
  "MAS_REQUIRE_CUDA=1"
  "PYTORCH_CUDA_ALLOC_CONF=${PYTORCH_CUDA_ALLOC_CONF_VALUE}"
  "MAS_LOG_DIR=${MAS_LOG_DIR_VALUE}"
  "MAS_PLOT_DIR=${MAS_PLOT_DIR_VALUE}"
  "MAS_THREE_LAYER_DEBUG_PRINT=${MAS_THREE_LAYER_DEBUG_PRINT_VALUE}"
  "MAS_PARALLEL_MODE=${MAS_PARALLEL_MODE_VALUE}"
  "MAS_POLICY_DEVICE_MAP=${MAS_POLICY_DEVICE_MAP_VALUE}"
  "MAS_GLOBAL_SEED=${MAS_GLOBAL_SEED_VALUE}"
)

if [[ -n "${MAS_TRAIN_VAL_TOTAL_LIMIT:-}" ]]; then
  CMD+=("MAS_TRAIN_VAL_TOTAL_LIMIT=${MAS_TRAIN_VAL_TOTAL_LIMIT}")
fi

if [[ -n "${MAS_TEST_SAMPLE_LIMIT:-}" ]]; then
  CMD+=("MAS_TEST_SAMPLE_LIMIT=${MAS_TEST_SAMPLE_LIMIT}")
fi

CMD+=("${ENV_PYTHON}" "${PROJECT_ROOT}/run_full_suite_4gpu.py")
"${CMD[@]}" 2>&1 | tee "${RUN_DIR}/train.log"
